### ISSUE TITLE
Remove Elements for not-logged-in Users

### ISSUE THREAD

**Issue by NikoHadouken** [verdigado/rallly#9]
Georg:

> Wenn ich mich als Gast einlogge, kann ich ohne Probleme teilnehmen.
> Im Frontend werden aber noch ein paar Sachen angezeigt, über die wir nachdenken sollten.
> Ich wäre für "ausblenden"

![image](https://github.com/user-attachments/assets/96dcfb0f-6a62-46b8-9c30-9db76354dada)

**Comment by NikoHadouken** [comment]
Willst du das ganze Menü weghaben oder nur einzelne Punkte?
Ich denke wir sollten das Menü besser unberührt lasstn.

der Link im Footer ist wieder hardcoded und lässt sich nur über Patch von Template anpassen.

**Comment by annaschwartze** [comment]
Stimmt, ohne wäre es schöner. Ich bin dennoch letzten Endes dafür, das Menü und den Hinweis auf Rallly lieber drin zu lassen. Wir haben ja noch ein paar Umsetzungen mit Luke vor und sollten in meinen Augen nicht riskieren, ihn vor allem durch Zweiteres zu verärgern.
